services:
  backend:
    image: "dto80/234-lab11:latest"
    ports:
      - "8084:8080"
    volumes:
      - type: bind
        source: ./xxx
        target: /data
  frontend:
    image: "bizhop17/se234-lab11-client:latest"
    ports:
      - "8083:80"
version: "3.3"